_wandb:
    value:
        cli_version: 0.27.2
        e:
            q18b0bzt7jw3jvv5r6lcbqbk581gpd81:
                codePath: /workspaces/DL-23f2003236-notebook-t22026/notebooks/02_preprocessing.ipynb
                codePathLocal: 02_preprocessing.ipynb
                cpu_count: 1
                cpu_count_logical: 2
                disk:
                    /:
                        total: "33636024320"
                        used: "25541398528"
                email: 23f2003236@ds.study.iitm.ac.in
                executable: /workspaces/DL-23f2003236-notebook-t22026/venv/bin/python
                git:
                    commit: 197f7d82e0d9aaf84d5c565ea50019862030d18f
                    remote: https://github.com/23f2003236/DL-23f2003236-notebook-t22026
                host: codespaces-24c8e2
                memory:
                    total: "8330444800"
                os: Linux-6.8.0-1052-azure-x86_64-with-glibc2.39
                program: /workspaces/DL-23f2003236-notebook-t22026/notebooks/02_preprocessing.ipynb
                python: CPython 3.12.1
                root: /workspaces/DL-23f2003236-notebook-t22026/notebooks
                startedAt: "2026-06-18T08:36:08.245771Z"
                writerId: q18b0bzt7jw3jvv5r6lcbqbk581gpd81
        m: []
        python_version: 3.12.1
        t:
            "3":
                - 2
                - 13
            "4": 3.12.1
            "5": 0.27.2
            "8":
                - 1
            "12": 0.27.2
            "13": linux-x86_64
